name: release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - uses: sigstore/cosign-installer@v1.2.0

    - name: Get Repo Owner
      id: get_repo_owner
      run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

    - name: Get tag
      id: get_tag
      run: echo ::set-output name=release_tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: login
      uses: docker/login-action@v1.10.0
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ steps.get_repo_owner.outputs.repo_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}