name: release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: sigstore/cosign-installer@v1.2.1

    - name: Get Repo Owner
      id: get_repo_owner
      run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')

    - name: Get tag
      id: get_tag
      run: echo ::set-output name=release_tag::${GITHUB_REF/refs\/tags\//}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: login
      uses: docker/login-action@v1.10.0
      if: ${{ github.event_name != 'pull_request' }}
      with:
        registry: ghcr.io
        username: ${{ steps.get_repo_owner.outputs.repo_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      uses: docker/build-push-action@v2.7.0
      with:
        platforms: linux/arm/v7
        push: true
        tags: ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/fan-control:${{ steps.get_tag.outputs.release_tag }}

    - name: Sign the images
      run: |
          cosign sign -key=cosign.key ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/fan-control:${{ steps.get_tag.outputs.release_tag }}
          docker logout
      shell: bash
      env:
        COSIGN_PASSWORD: ${{secrets.COSIGN_PASSWORD}}
